# Copyright 2019 CMCC Corporation.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Only used for local test
#First need to add broker('amqp://admin:mypass@rabbit:5672') to Celery

version: '2'
services:
    memcached:
        hostname: memcached
        image: memcached:alpine3.15
        command: ["memcached", "-m", "2048", "-c", "1024", "-p", "11211", "-P", "/tmp/memcached1.pid", "-v"]
        ports:
        - "11211:11211"

    worker:
        build:
            context: .
            dockerfile: ./pike/docker/Dockerfile4composer
        image: openstack-pike:test
        environment:
            - MEMCACHED_HOST=memcached
        # volumes:
        #     - .:/fcaps
