version: 1
disable_existing_loggers: False

loggers:
    fcaps:
      handlers: [fcaps_handler]
      level: "DEBUG"
      propagate: False
    newton_base:
      handlers: [fcaps_handler]
      level: "DEBUG"
      propagate: False
    common:
      handlers: [fcaps_handler]
      level: "DEBUG"
      propagate: False
    starlingx_base:
      handlers: [fcaps_handler]
      level: "DEBUG"
      propagate: False
handlers:
    fcaps_handler:
        level: "DEBUG"
        class: "logging.handlers.RotatingFileHandler"
        filename: "/var/log/onap/multicloud/openstack/fcaps/fcaps.log"
        formatter: "standard"
        maxBytes: 52428800
        backupCount: 10
formatters:
    standard:
        format: "%(asctime)s|||||%(name)s||%(thread)||%(funcName)s||%(levelname)s||%(message)s"
