$num_compute_nodes = 1

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-16.04"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 9192]
    vb.customize ["modifyvm", :id, "--cpus", 4]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    vb.customize "post-boot",["controlvm", :id, "setlinkstate1", "on"]
  end


  config.vm.define "control" do |config|
    config.vm.hostname = "control"
    config.vm.network "private_network", ip: "192.168.0.10"
    config.vm.network :private_network,  ip: "192.168.1.10"
    config.vm.provision "shell", path: "bootstrap.sh", privileged: false
    config.vm.provision "shell", path: "setup_control.sh", privileged: false
  end

  (1 .. $num_compute_nodes).each do |n|
    config.vm.define vm_name = "compute-#{n}" do |config|
      config.vm.hostname = vm_name
      config.vm.network "private_network", ip: "192.168.0.#{n+20}"
      config.vm.network :private_network,  ip: "192.168.1.#{n+20}"
      config.vm.provision "shell", path: "bootstrap.sh", privileged: false
      config.vm.provision "shell", path: "setup_compute.sh", privileged: false
    end
  end

  config.vm.define "onap" do |config|
    config.vm.hostname = "onap"
    config.vm.synced_folder "../..", "/openstack"
    config.vm.network "private_network", ip: "192.168.0.30"
    config.vm.network :private_network,  ip: "192.168.1.30"
    config.vm.provision "shell", path: "test/test_multicloud.sh", privileged: false
  end

end
