# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
$num_compute_nodes = 1

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", 9192]
    vb.customize ["modifyvm", :id, "--cpus", 4]
    vb.customize ["modifyvm", :id, "--nicpromisc3", "allow-all"]
    vb.customize "post-boot",["controlvm", :id, "setlinkstate1", "on"]
  end

  config.vm.define "control" do |config|
    config.vm.hostname = "control"
    config.vm.network :private_network, ip: "172.16.0.2", netmask: "255.255.255.0", auto_config: true   # Managment network
    config.vm.network :private_network, ip: "192.168.50.2", netmask: "255.255.255.0", auto_config: true # Public and External network
    config.vm.provision "shell", path: "bootstrap.sh"
    config.vm.provision "shell", path: "setup_control.sh"
  end

  config.vm.define "onap" do |config|
    config.vm.hostname = "onap"
    config.vm.synced_folder "../..", "/openstack"
    config.vm.network :private_network, ip: "172.16.0.3", netmask: "255.255.255.0", auto_config: true   # Managment network
    config.vm.network :private_network, ip: "192.168.50.3", netmask: "255.255.255.0", auto_config: true # Public and External network
    config.vm.provision "shell", path: "test/test_multicloud.sh", privileged: false
  end

  (1 .. $num_compute_nodes).each do |n|
    config.vm.define vm_name = "compute-#{n}" do |config|
      config.vm.hostname = vm_name
      config.vm.network :private_network, ip: "172.16.0.#{n+4}", netmask: "255.255.255.0", auto_config: true  # Managment network
      config.vm.network :private_network, ip: "192.168.1.#{n+4}", netmask: "255.255.255.0", auto_config: true # Public and External network
      config.vm.provision "shell", path: "bootstrap.sh"
      config.vm.provision "shell", path: "setup_compute.sh"
    end
  end


end
