
version: 1
disable_existing_loggers: False

loggers:
    starlingx_base:
      handlers: [console_handler, file_handler]
      level: "DEBUG"
      propagate: False
    starlingx:
      handlers: [console_handler, file_handler]
      level: "DEBUG"
      propagate: False
    newton_base:
      handlers: [console_handler, file_handler]
      level: "DEBUG"
      propagate: False
    common:
      handlers: [console_handler, file_handler]
      level: "DEBUG"
      propagate: False

handlers:
    console_handler:
        level: "DEBUG"
        class: "logging.StreamHandler"
        formatter: "standard"
    file_handler:
        level: "DEBUG"
        class: "logging.handlers.RotatingFileHandler"
        filename: "/var/log/onap/multicloud/openstack/windriver/titanium_cloud.log"
        formatter: "standard"
        maxBytes: 52428800
        backupCount: 10

formatters:
    standard:
        format: "%(asctime)s|||||%(name)s||%(thread)||%(funcName)s||%(levelname)s||%(message)s"
