version: 1
disable_existing_loggers: False

loggers:
    titanium_cloud:
      handlers: [titanium_cloud_handler]
      level: "DEBUG"
      propagate: False
    newton_base:
      handlers: [titanium_cloud_handler]
      level: "DEBUG"
      propagate: False
    common:
      handlers: [titanium_cloud_handler]
      level: "DEBUG"
      propagate: False
    starlingx_base:
      handlers: [titanium_cloud_handler]
      level: "DEBUG"
      propagate: False
handlers:
    titanium_cloud_handler:
        level: "DEBUG"
        class: "logging.handlers.RotatingFileHandler"
        filename: "/var/log/onap/multicloud/openstack/windriver/titanium_cloud.log"
        formatter: "standard"
        maxBytes: 52428800
        backupCount: 10
formatters:
    standard:
        format: "%(asctime)s|||||%(name)s||%(thread)||%(funcName)s||%(levelname)s||%(message)s"
